### ISSUE TITLE
Converting .sm Files Forces 4 Lanes For 5+ Lane Charts

### ISSUE THREAD

**Issue by HappyJuiceLive** [mtolly/onyx#256]
Hello! I noticed you specified support for .sm files, to have them translated to 5 frets. However whenever I import a .sm files with more than 4 lanes, it does not get recognized as an instrument at all. @mtolly 

If I try to convert it with the batch process instead of opening the full song, it WILL recognize and convert all the charts, but will force them to be 4 lanes when it was originally 5

**Comment by HappyJuiceLive** [comment]
![image](https://github.com/mtolly/onyx/assets/93631817/e722e822-e90a-48ac-9c1a-86ca68f3df90)
![2image](https://github.com/mtolly/onyx/assets/93631817/d47c09dd-ad33-4c88-aab3-5afa180518dd)

**Comment by mtolly** [comment]
Hi, sorry for the wait, this should be fixed in version `20240928` to support `.sm` with 5 or more keys. To convert such a chart to a 5-fret track, you'll want to either

* Use `Load a song` and manually select Dance from the Guitar dropdown on a target game tab
* Use `Batch recompile` and select a part configuration that copies "drums/dance" to guitar

Note that extended sustains (a hold note with other notes played in the middle of it) are only supported in some games/tracks. Rock Band only supports it on Keys, Clone Hero allows it on any track.

Let me know if there are any remaining issues here.
