### ISSUE TITLE
Apple Silicon version

### ISSUE THREAD

**Issue by Mrpink200** [mtolly/onyx#265]
Hello
Any version in the works (or trick to run Onyx on M1 / M2 chip) ??

Best Regards

**Comment by mtolly** [comment]
Hi, eventually this should happen but I probably won't have access to an Apple Silicon machine anytime soon to make that. However I have been told that the Intel build should work on M1 etc., there's just extra hoops to jump through since it is not notarized.

Did you try the steps from `IMPORTANT mac instructions.txt` in the zip file? I got that from https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/ , I tested on Intel but was told it worked on M1 also

**Comment by Mrpink200** [comment]
it works; many thx !!
